#pragma once

#include <builtinFonts/iawriterduo_12_bold.h>
#include <builtinFonts/iawriterduo_12_bold_2x.h>
#include <builtinFonts/iawriterduo_12_bolditalic.h>
#include <builtinFonts/iawriterduo_12_bolditalic_2x.h>
#include <builtinFonts/iawriterduo_12_italic.h>
#include <builtinFonts/iawriterduo_12_italic_2x.h>
#include <builtinFonts/iawriterduo_12_regular.h>
#include <builtinFonts/iawriterduo_12_regular_2x.h>
#include <builtinFonts/iawritermono_12_bold.h>
#include <builtinFonts/iawritermono_12_bold_2x.h>
#include <builtinFonts/iawritermono_12_bolditalic.h>
#include <builtinFonts/iawritermono_12_bolditalic_2x.h>
#include <builtinFonts/iawritermono_12_italic.h>
#include <builtinFonts/iawritermono_12_italic_2x.h>
#include <builtinFonts/iawritermono_12_regular.h>
#include <builtinFonts/iawritermono_12_regular_2x.h>
#include <builtinFonts/iawriterquattro_12_bold.h>
#include <builtinFonts/iawriterquattro_12_bold_2x.h>
#include <builtinFonts/iawriterquattro_12_bolditalic.h>
#include <builtinFonts/iawriterquattro_12_bolditalic_2x.h>
#include <builtinFonts/iawriterquattro_12_italic.h>
#include <builtinFonts/iawriterquattro_12_italic_2x.h>
#include <builtinFonts/iawriterquattro_12_regular.h>
#include <builtinFonts/iawriterquattro_12_regular_2x.h>
#include <builtinFonts/ibmplexmono_12_bold.h>
#include <builtinFonts/ibmplexmono_12_bold_2x.h>
#include <builtinFonts/ibmplexmono_12_bolditalic.h>
#include <builtinFonts/ibmplexmono_12_bolditalic_2x.h>
#include <builtinFonts/ibmplexmono_12_italic.h>
#include <builtinFonts/ibmplexmono_12_italic_2x.h>
#include <builtinFonts/ibmplexmono_12_regular.h>
#include <builtinFonts/ibmplexmono_12_regular_2x.h>
#include <builtinFonts/librefranklin_10_bold.h>
#include <builtinFonts/librefranklin_10_bold_2x.h>
#include <builtinFonts/librefranklin_10_regular.h>
#include <builtinFonts/librefranklin_10_regular_2x.h>
#include <builtinFonts/librefranklin_12_bold.h>
#include <builtinFonts/librefranklin_12_bold_2x.h>
#include <builtinFonts/librefranklin_12_regular.h>
#include <builtinFonts/librefranklin_12_regular_2x.h>
#include <builtinFonts/librefranklin_8_bold.h>
#include <builtinFonts/librefranklin_8_bold_2x.h>
#include <builtinFonts/librefranklin_8_regular.h>
#include <builtinFonts/librefranklin_8_regular_2x.h>
#include <builtinFonts/librefranklin_reader_12_bold.h>
#include <builtinFonts/librefranklin_reader_12_bolditalic.h>
#include <builtinFonts/librefranklin_reader_12_italic.h>
#include <builtinFonts/librefranklin_reader_12_regular.h>
#include <builtinFonts/librefranklin_reader_14_bold.h>
#include <builtinFonts/librefranklin_reader_14_bolditalic.h>
#include <builtinFonts/librefranklin_reader_14_italic.h>
#include <builtinFonts/librefranklin_reader_14_regular.h>
#include <builtinFonts/librefranklin_reader_16_bold.h>
#include <builtinFonts/librefranklin_reader_16_bolditalic.h>
#include <builtinFonts/librefranklin_reader_16_italic.h>
#include <builtinFonts/librefranklin_reader_16_regular.h>
#include <builtinFonts/librefranklin_reader_18_bold.h>
#include <builtinFonts/librefranklin_reader_18_bolditalic.h>
#include <builtinFonts/librefranklin_reader_18_italic.h>
#include <builtinFonts/librefranklin_reader_18_regular.h>
