import os
import re
import gzip

SRC_DIR = "src"

def minify_css(css: str) -> str:
    """Conservative CSS minification: strip block comments and blank lines.

    Only /* ... */ comments are removed; string literals in CSS rules are
    never multi-line, so a cross-line regex match cannot hit a false positive
    inside a string value in practice.  Trailing/leading whitespace on each
    line is left intact to avoid altering selector specificity or calc()
    expressions.
    """
    css = re.sub(r'/\*.*?\*/', '', css, flags=re.DOTALL)
    # Drop lines that became blank after comment removal
    lines = [l for l in css.splitlines() if l.strip()]
    return '\n'.join(lines) + '\n' if lines else ''


def minify_js(js: str) -> str:
    """Conservative JS minification: strip comment-only lines and blank lines.

    Only lines whose *entire* content (after stripping leading whitespace) is a
    // comment are removed.  Inline comments after code are left untouched,
    so URLs like https://... and regex literals are safe.  This avoids the
    complex state-machine needed for full tokenisation while still trimming the
    ~20 KB of developer comments found in FilesPage.html.
    """
    out = []
    for line in js.splitlines(keepends=True):
        if line.strip().startswith('//'):
            continue
        if not line.strip():
            continue
        out.append(line)
    return ''.join(out)


def minify_html(html: str) -> str:
    # Tags where whitespace must be fully preserved (no minification at all)
    preserve_tags = ['pre', 'code', 'textarea']
    preserve_regex = '|'.join(preserve_tags)

    # Protect preserve blocks with placeholders
    preserve_blocks = []
    def preserve(match):
        preserve_blocks.append(match.group(0))
        return f"__PRESERVE_BLOCK_{len(preserve_blocks)-1}__"

    html = re.sub(rf'<({preserve_regex})[\s\S]*?</\1>', preserve, html, flags=re.IGNORECASE)

    # Minify inline <style> blocks (CSS comment stripping)
    def minify_style_tag(match):
        open_tag, inner, close_tag = match.group(1), match.group(2), match.group(3)
        return open_tag + minify_css(inner) + close_tag
    html = re.sub(r'(<style[^>]*>)([\s\S]*?)(</style>)', minify_style_tag, html, flags=re.IGNORECASE)

    # Minify inline <script> blocks (comment-only line stripping)
    def minify_script_tag(match):
        open_tag, inner, close_tag = match.group(1), match.group(2), match.group(3)
        return open_tag + minify_js(inner) + close_tag
    html = re.sub(r'(<script[^>]*>)([\s\S]*?)(</script>)', minify_script_tag, html, flags=re.IGNORECASE)

    # Remove HTML comments
    html = re.sub(r'<!--.*?-->', '', html, flags=re.DOTALL)

    # Collapse all whitespace between tags
    html = re.sub(r'>\s+<', '><', html)

    # Collapse multiple spaces inside tags
    html = re.sub(r'\s+', ' ', html)

    # Restore preserved blocks
    for i, block in enumerate(preserve_blocks):
        html = html.replace(f"__PRESERVE_BLOCK_{i}__", block)

    return html.strip()

def sanitize_identifier(name: str) -> str:
    """Sanitize a filename to create a valid C identifier.

    C identifiers must:
    - Start with a letter or underscore
    - Contain only letters, digits, and underscores
    """
    # Replace non-alphanumeric characters (including hyphens) with underscores
    sanitized = re.sub(r'[^a-zA-Z0-9_]', '_', name)
    # Prefix with underscore if starts with a digit
    if sanitized and sanitized[0].isdigit():
        sanitized = f"_{sanitized}"
    return sanitized

for root, _, files in os.walk(SRC_DIR):
    for file in files:
        if file.endswith(".html") or file.endswith(".js"):
            file_path = os.path.join(root, file)
            with open(file_path, "r", encoding="utf-8") as f:
                content = f.read()

            # Only minify HTML files; JS files are typically pre-minified (e.g., jszip.min.js)
            if file.endswith(".html"):
                processed = minify_html(content)
            else:
                processed = content

            # Compress with gzip (compresslevel 9 is maximum compression)
            # IMPORTANT: we don't use brotli because Firefox doesn't support brotli with insecured context (only supported on HTTPS)
            compressed = gzip.compress(processed.encode('utf-8'), compresslevel=9)

            # Create valid C identifier from filename
            # Use appropriate suffix based on file type
            suffix = "Html" if file.endswith(".html") else "Js"
            base_name = sanitize_identifier(f"{os.path.splitext(file)[0]}{suffix}")
            header_path = os.path.join(root, f"{base_name}.generated.h")

            with open(header_path, "w", encoding="utf-8") as h:
                h.write(f"// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY\n\n")
                h.write(f"#pragma once\n")
                h.write(f"#include <cstddef>\n\n")

                # Write the compressed data as a byte array
                h.write(f"constexpr char {base_name}[] PROGMEM = {{\n")

                # Write bytes in rows of 16
                for i in range(0, len(compressed), 16):
                    chunk = compressed[i:i+16]
                    hex_values = ', '.join(f'0x{b:02x}' for b in chunk)
                    h.write(f"  {hex_values},\n")

                h.write(f"}};\n\n")
                h.write(f"constexpr size_t {base_name}CompressedSize = {len(compressed)};\n")
                h.write(f"constexpr size_t {base_name}OriginalSize = {len(processed)};\n")

            print(f"Generated: {header_path}")
            print(f"  Original: {len(content)} bytes")
            print(f"  Minified: {len(processed)} bytes ({100*len(processed)/len(content):.1f}%)")
            print(f"  Compressed: {len(compressed)} bytes ({100*len(compressed)/len(content):.1f}%)")
