#!/usr/bin/env python3
"""Generate the UI icon bitmaps from Lucide SVGs.

Emits the SAME `static const uint8_t <Name>[]` format the hand-drawn headers in
src/components/icons/ already use, so GfxRenderer::drawIcon and
LyraTheme::iconForName need no changes -- only the artwork moves.

WHY NOT THE SDK'S GENERATOR (libs/assets/Icons/tools/gen_icons.py)

That one emits freeink::Icon structs whose bits are deliberately NOT pre-rotated:
its renderer maps logical coordinates to the panel itself. This firmware's
drawIcon does not. It plots stored (row, col) to screen (x + size-1-row, y + col)
-- a 90 degree turn baked into the draw, with a comment saying it reproduces the
orientation the old byte-aligned blit produced. The existing assets are stored
pre-rotated so the two cancel.

Feed a non-rotated asset to that drawIcon and it ships sideways. So this script
rotates the raster 90 CCW before packing, which is what the current headers
already do -- confirmed by decoding wifi.h: read row-major it is sideways, turned
90 CW it is a correct wifi glyph.

If drawIcon ever stops rotating, delete the rotate here in the same commit.

Requires: rsvg-convert (brew install librsvg) and Pillow.

Usage:
    scripts/gen_lucide_icons.py --out src/components/icons/lucide_icons.h
"""
import argparse
import io
import os
import subprocess
import sys

from PIL import Image

# Owner rulings, 2026-08-07. See TODO.md T-001 for the chooser page these came
# from. Left is the C identifier stem, right is the SVG basename.
ICONS = [
    ("Folder", "folder"),
    ("Text", "file-text"),
    ("Image", "image"),
    ("Book", "book"),
    ("File", "file"),
    ("Recent", "clock"),
    ("Settings", "settings-2"),
    ("Transfer", "arrow-right-left"),
    ("Library", "library-big"),
    ("Wifi", "wifi"),
    ("Hotspot", "radio"),
    ("ManageFiles", "folder-cog"),
    ("CreateNote", "square-pen"),
    # Not a Lucide icon: the real Claude mark, filled rather than stroked, because
    # a stroked approximation of it reads as a generic snowflake and not as the
    # mark. Lucide `bot` is the sanctioned fallback if the mark is ever unwanted.
    ("ClaudeMark", "claude-mark"),
    # The one-button firmware update on Home. cloud-download rather than
    # refresh-cw: this pulls a release off GitHub, and a recycle arrow reads as
    # "reload this screen" next to six rows that all open something.
    ("Update", "cloud-download"),
]

SIZES = (24, 32)

# Luminance below this (composited on white) counts as ink. Same value the SDK
# generator uses; it keeps a 2px Lucide stroke solid at 24px.
THRESHOLD = 110


def rasterize(svg_path, px):
    png = subprocess.run(
        ["rsvg-convert", "-w", str(px), "-h", str(px), svg_path],
        capture_output=True, check=True,
    ).stdout
    img = Image.open(io.BytesIO(png)).convert("RGBA")
    bg = Image.new("RGBA", img.size, (255, 255, 255, 255))
    bg.paste(img, mask=img.split()[3])
    return bg.convert("L")


def pack(img, px):
    """1bpp, MSB-first, bit 1 = leave, bit 0 = ink -- drawIcon's convention."""
    pix = img.load()
    out = []
    for y in range(px):
        for xb in range(0, px, 8):
            byte = 0
            for b in range(8):
                x = xb + b
                white = 1
                if x < px and pix[x, y] < THRESHOLD:
                    white = 0
                byte |= white << (7 - b)
            out.append(byte)
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--svgdir", default="freeink-sdk/libs/assets/Icons/lucide/icons")
    ap.add_argument("--extradir", default="src/components/icons")
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    lines = [
        "#pragma once",
        "#include <cstdint>",
        "",
        "// GENERATED by scripts/gen_lucide_icons.py from Lucide SVGs. Do not edit.",
        "//",
        "// Stored PRE-ROTATED 90 CCW. GfxRenderer::drawIcon plots stored (row, col)",
        "// to screen (x + size-1-row, y + col), so the asset has to be turned the",
        "// other way for the two to cancel. Regenerate rather than hand-editing.",
        "",
    ]
    made = 0
    for stem, svg_name in ICONS:
        path = os.path.join(args.svgdir, svg_name + ".svg")
        if not os.path.exists(path):
            path = os.path.join(args.extradir, svg_name + ".svg")
        if not os.path.exists(path):
            print(f"ERROR: no svg for {stem} ({svg_name})", file=sys.stderr)
            return 1
        for px in SIZES:
            img = rasterize(path, px)
            # The pre-rotation. ROTATE_90 is counter-clockwise in Pillow.
            img = img.transpose(Image.ROTATE_90)
            data = pack(img, px)
            name = f"{stem}{px}LucideIcon"
            body = ",\n    ".join(
                ", ".join(f"0x{b:02X}" for b in data[i:i + 12])
                for i in range(0, len(data), 12)
            )
            lines += [
                f"// {svg_name} @ {px}px",
                f"static const uint8_t {name}[] = {{",
                f"    {body}}};",
                "",
            ]
            made += 1
    open(args.out, "w").write("\n".join(lines))
    print(f"wrote {args.out}: {made} bitmaps ({len(ICONS)} icons x {len(SIZES)} sizes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
