// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

// Libre Franklin reader cuts — the only built-in reading family (owner ruling
// 2026-08-07; Noto Serif, Noto Sans and Ubuntu removed). Added by hand like the
// editor monospace ids below: the values are opaque handles (insertFont/drawText
// keys; SdCardFontManager::computeFontId guards collisions at runtime), checked
// non-zero and non-colliding when added.
#define LIBREFRANKLIN_READER_12_FONT_ID (912744121)
#define LIBREFRANKLIN_READER_14_FONT_ID (-1054793780)
#define LIBREFRANKLIN_READER_16_FONT_ID (1734005343)
#define LIBREFRANKLIN_READER_18_FONT_ID (-421869102)
#define UI_10_FONT_ID (22918846)
#define UI_12_FONT_ID (1635686837)
#define SMALL_FONT_ID (674098198)

// Editor-group fonts, compiled into the firmware rather than loaded from the
// card. resolveEditorFont() asks for ONE size, 12 pt, in four styles, so only
// that cut of each family exists. Flash cost, compressed: ~83 KB for the two
// Google Fonts monos (SpaceMono + IBMPlexMono, owner ruling 2026-08-06) plus
// ~216 KB for the three iA Writer families (owner ruling 2026-08-11). The _2x
// companions (~818 KB compressed total) are dead flash on device where
// RENDER_SCALE=1 and are stripped by --gc-sections; they are present only for
// the simulator / iOS builds that run at RENDER_SCALE=2.
//
// Added by hand, NOT by build-font-ids.sh, and two things are worth knowing
// before anyone regenerates: the script needs ruby, which is not configured
// here (.tool-versions asks for 3.2.0), and the IDs it emits today do not
// match the eleven above — the builtin headers have been regenerated since
// fontIds.h was last built, so every hash has moved. The values are opaque
// handles (insertFont/drawText keys; SdCardFontManager::computeFontId guards
// collisions at runtime), so being stale is harmless, but a regen would churn
// all of them for nothing. All checked non-zero and non-colliding when added.
#define IBMPLEXMONO_12_FONT_ID (-1793317468)
#define IAWRITERQUATTRO_12_FONT_ID (491272101)
#define IAWRITERDUO_12_FONT_ID (-672455302)
#define IAWRITERMONO_12_FONT_ID (1291847533)

// PragmataPro is the one editor face whose glyph tables are NOT in this repo.
// It is commercial, so builtinFonts/pragmatapro_*.h are gitignored and built
// locally from lib/EpdFont/local_fonts/. The ID is declared unconditionally --
// it is just an opaque handle, and EditorFonts.h's table needs a stable value
// for the persisted row regardless of whether this build has the glyphs.
// main.cpp registers the family only when __has_include finds the headers, and
// editorfonts::resolve() already refuses to hand back an id the renderer has no
// glyphs for, so a tree without the font degrades to a built-in mono.
#define PRAGMATAPRO_12_FONT_ID (1544097263)

// NittiTypewriter is also COMMERCIAL (Pieter van Rosmalen / Bold Monday).
// Same treatment as PragmataPro: ID declared unconditionally, glyph tables
// gitignored (builtinFonts/nitti*.h), main.cpp registers only when
// __has_include finds them. Unlike PragmataPro, only a Regular TTF is
// available; Bold/Italic/BoldItalic are synthesised at build time via
// fontconvert.py's --synth-embolden-em / --synth-slant-deg flags.
#define NITTITYPEWRITER_12_FONT_ID (738591204)

// Font ID 0 is reserved as the "not found" sentinel.
// Guard against any hash accidentally producing 0.
static_assert(LIBREFRANKLIN_READER_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LIBREFRANKLIN_READER_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LIBREFRANKLIN_READER_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LIBREFRANKLIN_READER_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SMALL_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(IBMPLEXMONO_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(IAWRITERQUATTRO_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(IAWRITERDUO_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(IAWRITERMONO_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(PRAGMATAPRO_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NITTITYPEWRITER_12_FONT_ID != 0, "Font ID collision with sentinel");
