// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

// Libre Franklin reader cuts — the only built-in reading family (owner ruling
// 2026-08-07; Noto Serif, Noto Sans and Ubuntu removed). Added by hand like the
// editor monospace ids below: the values are opaque handles (insertFont/drawText
// keys; SdCardFontManager::computeFontId guards collisions at runtime), checked
// non-zero and non-colliding when added.
// XXS and XS, added 2026-08-26 (owner: "cut XS and XXS versions of every s
// tiers shipping font"). The built-in ramp keeps its own 2 pt step and extends
// downward to 8/10 rather than adopting the SD families' point sizes; the
// offset between the two ramps is measured in ReaderFontSizes.h. Values are
// the same SHA-256-sum-mod-2^32 build-font-ids.sh computes over the four style
// headers, checked non-zero and non-colliding against every id in this file.
#define LIBREFRANKLIN_READER_8_FONT_ID (-1089830612)
#define LIBREFRANKLIN_READER_10_FONT_ID (-1064831052)
#define LIBREFRANKLIN_READER_12_FONT_ID (912744121)
#define LIBREFRANKLIN_READER_14_FONT_ID (-1054793780)
#define LIBREFRANKLIN_READER_16_FONT_ID (1734005343)
#define LIBREFRANKLIN_READER_18_FONT_ID (-421869102)
#define UI_10_FONT_ID (22918846)
#define UI_12_FONT_ID (1635686837)
#define SMALL_FONT_ID (674098198)

// Noto Sans, the COVERAGE face behind the chrome (owner instruction 2026-08-17,
// "put noto sans in as builtin"). Not a chrome family -- Libre Franklin is
// still the only face the UI draws with -- these ids exist so the renderer can
// be told to fall back to them for a codepoint Libre Franklin lacks: 2,965
// codepoints against its 918, which is where Greek, Cyrillic and the rest of
// Latin Extended come from in a title or a filename.
//
// Hand-picked like the ids above and for the same reason: build-font-ids.sh
// still hashes ubuntu_*/notosans_* headers that were deleted with those
// families, so it cannot be run to generate these. Chosen well away from the
// existing values and checked against every id in this file.
#define NOTOSANS_UI_8_FONT_ID (511000801)
#define NOTOSANS_UI_10_FONT_ID (511001001)
#define NOTOSANS_UI_12_FONT_ID (511001201)

// Editor-group fonts, compiled into the firmware rather than loaded from the
// card. resolveEditorFont() asks for TWO sizes, 12 and 14 pt (owner ruling
// 2026-08-15), in four styles each. THREE families as of the 2026-08-15 ruling:
// iA Writer Quattro (OFL, in this repo) plus the two commercial faces below.
// Space Mono, IBM Plex Mono, iA Writer Duo and iA Writer Mono were all removed
// that day; their ids are gone, their generated headers stay tracked. The _2x
// companions are dead flash on device where
// RENDER_SCALE=1 and are stripped by --gc-sections; they are present only for
// the simulator / iOS builds that run at RENDER_SCALE=2.
//
// Added by hand, NOT by build-font-ids.sh, and two things are worth knowing
// before anyone regenerates: the script needs ruby, which is not configured
// here (.tool-versions asks for 3.2.0), and the IDs it emits today do not
// match the ids above — the builtin headers have been regenerated since
// fontIds.h was last built, so every hash has moved. The values are opaque
// handles (insertFont/drawText keys; SdCardFontManager::computeFontId guards
// collisions at runtime), so being stale is harmless, but a regen would churn
// all of them for nothing. All checked non-zero and non-colliding when added.
#define IAWRITERQUATTRO_12_FONT_ID (491272101)
#define IAWRITERQUATTRO_14_FONT_ID (913617268)

// PragmataPro is the one editor face whose glyph tables are NOT in this repo.
// It is commercial, so builtinFonts/pragmatapro_*.h are gitignored and built
// locally from lib/EpdFont/local_fonts/. The ID is declared unconditionally --
// it is just an opaque handle, and EditorFonts.h's table needs a stable value
// for the persisted row regardless of whether this build has the glyphs.
// main.cpp registers the family only when __has_include finds the headers, and
// editorfonts::resolve() already refuses to hand back an id the renderer has no
// glyphs for, so a tree without the font degrades to a built-in mono.
#define PRAGMATAPRO_12_FONT_ID (1544097263)
#define PRAGMATAPRO_14_FONT_ID (1474155098)

// NittiTypewriter is also COMMERCIAL (Pieter van Rosmalen / Bold Monday).
// Same treatment as PragmataPro: ID declared unconditionally, glyph tables
// gitignored (builtinFonts/nitti*.h), main.cpp registers only when
// __has_include finds them. Unlike PragmataPro, only a Regular TTF is
// available; Bold/Italic/BoldItalic are synthesised at build time via
// fontconvert.py's --synth-embolden-em / --synth-slant-deg flags.
#define NITTITYPEWRITER_12_FONT_ID (738591204)
#define NITTITYPEWRITER_14_FONT_ID (1881475312)

// Font ID 0 is reserved as the "not found" sentinel.
// Guard against any hash accidentally producing 0.
static_assert(LIBREFRANKLIN_READER_8_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LIBREFRANKLIN_READER_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LIBREFRANKLIN_READER_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LIBREFRANKLIN_READER_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LIBREFRANKLIN_READER_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LIBREFRANKLIN_READER_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SMALL_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(IAWRITERQUATTRO_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(IAWRITERQUATTRO_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(PRAGMATAPRO_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(PRAGMATAPRO_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NITTITYPEWRITER_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NITTITYPEWRITER_14_FONT_ID != 0, "Font ID collision with sentinel");
