#pragma once

#include <cstddef>
#include <cstdint>

// The code-page data behind the expat unknown-encoding handler, kept PURE: no
// expat, no storage, no book notes, nothing this repo cannot compile on a host.
// A wrong table is silent -- the chapter parses, and every accented word in it
// is a different accented word -- so this half is the half that gets a
// round-trip test (test/xml_encodings) against Python's own codecs.
//
// XmlEncodingTables.cpp is GENERATED by tools/gen_xml_encodings.py.
namespace xmlencodings {

// Bytes 0x80..0xFF of `declaredName`'s code page as Unicode scalars, or nullptr
// when this firmware carries no table for that name. 0xFFFD marks a byte the
// code page leaves undefined. The low half is never returned: every code page
// here is ASCII-identical below 0x80, which expat requires and the generator
// enforces.
//
// Matching is on the NORMALISED name, so "Windows-1252", "windows_1252" and
// "CP1252" are one encoding.
const uint16_t* highHalfFor(const char* declaredName);

// Lowercase, letters and digits only, truncated to fit. Exposed because the
// test drives it directly: the normalisation is where a plausible-looking alias
// list stops matching real declarations.
void normaliseEncodingName(const char* name, char* out, size_t outSize);

extern const size_t kSingleByteEncodingCount;
extern const size_t kEncodingAliasCount;

}  // namespace xmlencodings
